<template>

    <div class="rebate">
        <div class="top">
            <a href="javascript:;" class="btn font0 back">返回</a>
            <a href="#" class="btn date-rebate">日期选择</a>
            <h1>返佣详情</h1>
        </div>
        <div class="rebate-msg">
            <ul>
                <li class="rebate-msg1">
                    <span>总投注</span>
                    <div>65.3万</div>
                </li>
                <li class="rebate-msg2">
                    <span>总盈亏</span>
                    <div>62万</div>
                </li>
            </ul>
        </div>

        <div class="rebate-view">
            <div class="view-t">
                <ul>
                    <li>用户</li>
                    <li>投注</li>
                    <li>盈亏</li>
                    <li>手续费</li>
                    <li>奖品成本</li>
                </ul>
            </div>
            <div class="view-c">
                <ul>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>133</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>144</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>133</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>144</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>333</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>5</span>
                    </li>
                    <li>
                        <span>1</span>
                        <span>2</span>
                        <span>3</span>
                        <span>4</span>
                        <span>final</span>
                    </li>
                </ul>
>>>>>>> 91ff372d9b9f7209727ecc7b8caae8c02f20c09f
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data(){
            return {
                title: ''
            }
        },
        watch: {},
        methods: {},
        computed: {},
        mounted(){

        }
    }
</script>
<style>
    html,body,.wrapper{
        height:100%;
        overflow: hidden;
    }
</style>
